version: '3.8'

services:
  myfinance-backend:
    build: .
    container_name: myfinance-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
      - '4000:4000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
